# Generated by Django 5.0 on 2023-12-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(max_length=1),
        ),
    ]
