# Generated by Django 5.0 on 2023-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_details", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicedetails",
            name="cgst",
        ),
        migrations.RemoveField(
            model_name="invoicedetails",
            name="sgst",
        ),
        migrations.AddField(
            model_name="invoice",
            name="cgst",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
